### ISSUE TITLE
Wrong scenario namespace in perfcake-5.1.jar released into Maven Repository

### ISSUE THREAD

**Issue by pmacik** [PerfCake/PerfCake#259]
A package info (org.perfcake.model.package-info.java) that is part of released perfcake-5.1.jar found in Maven Repository (http://repo1.maven.org/maven2/org/perfcake/perfcake/5.1/perfcake-5.1.jar) has wrong namespace property value of javax.xml.bind.annotation.XmlSchema annotation.

In the JAR file that is released in Maven Repository there is a namespace value "urn:perfcake:scenario:6.0" instead of correct "urn.perfcake:scenario:5.0".

That causes following exception to rise when using perfcake from maven as a dependency:
2015-10-30 14:17:46,377 INFO  {org.perfcake.scenario.ScenarioBuilder} Scenario configuration: file:/home/pmacik/perfcake-5.1/resources/scenarios/http.xml
2015-10-30 14:17:46,516 FATAL {org.perfcake.ScenarioExecution} Cannot load scenario 'http': 
org.perfcake.PerfCakeException: Cannot parse scenario configuration: 
	at org.perfcake.scenario.XmlFactory.parse(XmlFactory.java:211) ~[perfcake-5.1.jar:?]
	at org.perfcake.scenario.XmlFactory.prepareModelTwoPass(XmlFactory.java:139) ~[perfcake-5.1.jar:?]
	at org.perfcake.scenario.XmlFactory.init(XmlFactory.java:115) ~[perfcake-5.1.jar:?]
	at org.perfcake.scenario.ScenarioLoader.load(ScenarioLoader.java:75) ~[perfcake-5.1.jar:?]
	at org.perfcake.ScenarioExecution.loadScenario(ScenarioExecution.java:236) [perfcake-5.1.jar:?]
	at org.perfcake.ScenarioExecution.<init>(ScenarioExecution.java:85) [perfcake-5.1.jar:?]
	at org.perfcake.ScenarioExecution.main(ScenarioExecution.java:95) [perfcake-5.1.jar:?]
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"urn:perfcake:scenario:5.0", local:"scenario"). Expected elements are <{urn:perfcake:scenario:6.0}header>,<{urn:perfcake:scenario:6.0}property>,<{urn:perfcake:scenario:6.0}scenario>
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726) ~[?:1.8.0_60]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247) ~[?:1.8.0_60]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242) ~[?:1.8.0_60]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109) ~[?:1.8.0_60]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1131) ~[?:1.8.0_60]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556) ~[?:1.8.0_60]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538) ~[?:1.8.0_60]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.startElement(ValidatingUnmarshaller.java:87) ~[?:1.8.0_60]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:379) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:605) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3138) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[?:1.8.0_60]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649) ~[?:1.8.0_60]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243) ~[?:1.8.0_60]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214) ~[?:1.8.0_60]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) ~[?:1.8.0_60]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:125) ~[?:1.8.0_60]
	at org.perfcake.scenario.XmlFactory.parse(XmlFactory.java:207) ~[perfcake-5.1.jar:?]
	... 6 more

**Comment by pmacik** [comment]
I've checked the perfcake-5.1.jar in binary distribution available on https://www.perfcake.org/download/ and the JAR file there is OK.

**Comment by pmacik** [comment]
Fixed... Closing.
Thanks, Martin.
