### ISSUE TITLE
RequestResponseJmsSender incorrectly handles default response* properties.

### ISSUE THREAD

**Issue by pmacik** [PerfCake/PerfCake#330]
The sender is, by default, supposed to re-use JNDI and JMS related connection properties for the response part - to use the same as for request.

It does not do that correctly.

When all response* properties are set explicitly in the scenario, the sender behaves as expected.

**Comment by pmacik** [comment]
With the inception of receivers the sender will probably become obsolete in the future. The receivers are to be "technological preview" in release 7, so the sender should be fixed anyway.

**Comment by pmacik** [comment]
The following exception is thrown:
`2016-07-19 06:36:17,483 FATAL [org.perfcake.ScenarioExecution.main()] {org.perfcake.ScenarioExecution} Error running scenario: 
org.perfcake.PerfCakeException: Cannot initialize message generator: 
	at org.perfcake.scenario.Scenario.init(Scenario.java:100) ~[perfcake-6.2.jar:?]
	at org.perfcake.ScenarioExecution.executeScenario(ScenarioExecution.java:254) [perfcake-6.2.jar:?]
	at org.perfcake.ScenarioExecution.main(ScenarioExecution.java:102) [perfcake-6.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297) [exec-maven-plugin-1.2.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: org.perfcake.PerfCakeException: Unable to instantiate sender class: 
	at org.perfcake.message.sender.MessageSenderManager.init(MessageSenderManager.java:116) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.generator.AbstractMessageGenerator.init(AbstractMessageGenerator.java:103) ~[perfcake-6.2.jar:?]
	at org.perfcake.scenario.Scenario.init(Scenario.java:98) ~[perfcake-6.2.jar:?]
	... 8 more
Caused by: org.perfcake.PerfCakeException: javax.naming.AuthenticationException: Failed to connect to any server. Servers tried: [remote://jawa09:4447 (Authentication failed: all available authentication mechanisms failed)] [Root exception is javax.security.sasl.SaslException: Authentication failed: all available authentication mechanisms failed]
	at org.perfcake.message.sender.RequestResponseJmsSender.initResponseConnection(RequestResponseJmsSender.java:202) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.RequestResponseJmsSender.doInit(RequestResponseJmsSender.java:157) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.AbstractSender.init(AbstractSender.java:61) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.MessageSenderManager.addSenderInstance(MessageSenderManager.java:130) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.MessageSenderManager.init(MessageSenderManager.java:114) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.generator.AbstractMessageGenerator.init(AbstractMessageGenerator.java:103) ~[perfcake-6.2.jar:?]
	at org.perfcake.scenario.Scenario.init(Scenario.java:98) ~[perfcake-6.2.jar:?]
	... 8 more
Caused by: javax.naming.AuthenticationException: Failed to connect to any server. Servers tried: [remote://jawa09:4447 (Authentication failed: all available authentication mechanisms failed)]
	at org.jboss.naming.remote.client.HaRemoteNamingStore.failOverSequence(HaRemoteNamingStore.java:237) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.HaRemoteNamingStore.namingStore(HaRemoteNamingStore.java:149) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.HaRemoteNamingStore.namingOperation(HaRemoteNamingStore.java:130) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.HaRemoteNamingStore.lookup(HaRemoteNamingStore.java:271) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.RemoteContext.lookupInternal(RemoteContext.java:104) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.RemoteContext.lookup(RemoteContext.java:93) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.RemoteContext.lookup(RemoteContext.java:146) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at javax.naming.InitialContext.lookup(InitialContext.java:417) ~[?:1.8.0_92]
	at org.perfcake.message.sender.RequestResponseJmsSender.initResponseConnection(RequestResponseJmsSender.java:194) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.RequestResponseJmsSender.doInit(RequestResponseJmsSender.java:157) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.AbstractSender.init(AbstractSender.java:61) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.MessageSenderManager.addSenderInstance(MessageSenderManager.java:130) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.MessageSenderManager.init(MessageSenderManager.java:114) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.generator.AbstractMessageGenerator.init(AbstractMessageGenerator.java:103) ~[perfcake-6.2.jar:?]
	at org.perfcake.scenario.Scenario.init(Scenario.java:98) ~[perfcake-6.2.jar:?]
	... 8 more
Caused by: javax.security.sasl.SaslException: Authentication failed: all available authentication mechanisms failed
	at org.jboss.remoting3.remote.ClientConnectionOpenListener$Capabilities.handleEvent(ClientConnectionOpenListener.java:365) ~[jboss-remoting-3.2.7.GA.jar:3.2.7.GA]
	at org.jboss.remoting3.remote.ClientConnectionOpenListener$Capabilities.handleEvent(ClientConnectionOpenListener.java:214) ~[jboss-remoting-3.2.7.GA.jar:3.2.7.GA]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:72) ~[xnio-api-3.0.0.GA.jar:3.0.0.GA]
	at org.xnio.channels.TranslatingSuspendableChannel.handleReadable(TranslatingSuspendableChannel.java:189) ~[xnio-api-3.0.0.GA.jar:3.0.0.GA]
	at org.xnio.channels.TranslatingSuspendableChannel$1.handleEvent(TranslatingSuspendableChannel.java:103) ~[xnio-api-3.0.0.GA.jar:3.0.0.GA]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:72) ~[xnio-api-3.0.0.GA.jar:3.0.0.GA]
	at org.xnio.nio.NioHandle.run(NioHandle.java:90) ~[xnio-nio-3.0.0.GA.jar:3.0.0.GA]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:184) ~[xnio-nio-3.0.0.GA.jar:3.0.0.GA]
	at ...asynchronous invocation...(Unknown Source) ~[?:?]
	at org.jboss.remoting3.EndpointImpl.doConnect(EndpointImpl.java:270) ~[jboss-remoting-3.2.7.GA.jar:3.2.7.GA]
	at org.jboss.remoting3.EndpointImpl.doConnect(EndpointImpl.java:251) ~[jboss-remoting-3.2.7.GA.jar:3.2.7.GA]
	at org.jboss.remoting3.EndpointImpl.connect(EndpointImpl.java:349) ~[jboss-remoting-3.2.7.GA.jar:3.2.7.GA]
	at org.jboss.remoting3.EndpointImpl.connect(EndpointImpl.java:333) ~[jboss-remoting-3.2.7.GA.jar:3.2.7.GA]
	at org.jboss.naming.remote.client.EndpointCache$EndpointWrapper.connect(EndpointCache.java:105) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.HaRemoteNamingStore.failOverSequence(HaRemoteNamingStore.java:197) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.HaRemoteNamingStore.namingStore(HaRemoteNamingStore.java:149) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.HaRemoteNamingStore.namingOperation(HaRemoteNamingStore.java:130) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.HaRemoteNamingStore.lookup(HaRemoteNamingStore.java:271) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.RemoteContext.lookupInternal(RemoteContext.java:104) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.RemoteContext.lookup(RemoteContext.java:93) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at org.jboss.naming.remote.client.RemoteContext.lookup(RemoteContext.java:146) ~[jboss-remote-naming-1.0.10.Final-redhat-1.jar:1.0.10.Final-redhat-1]
	at javax.naming.InitialContext.lookup(InitialContext.java:417) ~[?:1.8.0_92]
	at org.perfcake.message.sender.RequestResponseJmsSender.initResponseConnection(RequestResponseJmsSender.java:194) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.RequestResponseJmsSender.doInit(RequestResponseJmsSender.java:157) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.AbstractSender.init(AbstractSender.java:61) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.MessageSenderManager.addSenderInstance(MessageSenderManager.java:130) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.sender.MessageSenderManager.init(MessageSenderManager.java:114) ~[perfcake-6.2.jar:?]
	at org.perfcake.message.generator.AbstractMessageGenerator.init(AbstractMessageGenerator.java:103) ~[perfcake-6.2.jar:?]
	at org.perfcake.scenario.Scenario.init(Scenario.java:98) ~[perfcake-6.2.jar:?]
	... 8 more`

**Comment by pmacik** [comment]
The sender's behavior is correct after all, we need to better document it in User's guide.
