### ISSUE TITLE
ConcurrentModificationException when using time windowType in ThroughputStatsReporter

### ISSUE THREAD

**Issue by FilipB** [PerfCake/PerfCake#368]
Following exception is thrown when time windowType in ThroughputStatsReporter is used:

```
Exception in thread "Thread-2" java.util.ConcurrentModificationException
        at org.apache.commons.collections4.list.AbstractLinkedList$LinkedListIterator.checkModCount(AbstractLinkedList.java:801)
        at org.apache.commons.collections4.list.AbstractLinkedList$LinkedListIterator.next(AbstractLinkedList.java:824)
        at org.perfcake.common.TimeSlidingWindow.gc(TimeSlidingWindow.java:174)
        at org.perfcake.common.TimeSlidingWindow.gc(TimeSlidingWindow.java:161)
        at org.perfcake.common.TimeSlidingWindow.forEach(TimeSlidingWindow.java:124)
        at org.perfcake.reporting.reporter.accumulator.AbstractTimeSlidingWindowAccumulator.getResult(AbstractTimeSlidingWindowAccumulator.java:69)
        at org.perfcake.reporting.reporter.AbstractReporter.lambda$publishAccumulatedResult$14(AbstractReporter.java:169)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.perfcake.reporting.reporter.AbstractReporter.publishAccumulatedResult(AbstractReporter.java:169)
        at org.perfcake.reporting.reporter.StatsReporter.publishResult(StatsReporter.java:257)
        at org.perfcake.reporting.ReportManager.lambda$start$8(ReportManager.java:289)
        at java.lang.Thread.run(Thread.java:745)
```

When using "iteration" type it's working correctly.
Log, scenario and thread dump are attached.
[scenario-logs.tar.gz](https://github.com/PerfCake/PerfCake/files/527494/scenario-logs.tar.gz)

**Comment by pmacik** [comment]
# Reproducer
## Weaver:
```
100x DelayWorker=delay:10
```
## PerfCake scenario:
```xml
<?xml version="1.0" encoding="utf-8"?>
<scenario xmlns="urn:perfcake:scenario:7.0">
	<run type="${perfcake.performance.run.type:time}" value="${perfcake.performance.run.duration:300000}"/>
	<generator class="DefaultMessageGenerator" threads="${perfcake.performance.thread.count:100}"/>
	<sequences>
		<sequence class="ThreadIdSequence" id="threadId"/>
	</sequences>
	<sender class="HttpSender">
		<target>http://localhost:8080</target>
		<property name="method" value="POST"/>
	</sender>
	<reporting>
		<reporter class="WarmUpReporter" enabled="${perfcake.performance.warmup.enabled:true}">
			<property name="relativeThreshold" value="0.005"/>
			<property name="absoluteThreshold" value="0.5"/>
		</reporter>
		<reporter class="ResponseTimeStatsReporter">
			<property name="windowSize" value="5000"/>
			<property name="windowType" value="time"/>
			<destination class="CsvDestination">
				<period type="time" value="5000"/>
				<property name="path" value="${perfcake.scenario}-response-time-stats-${perfcake.run.nice.timestamp}.csv"/>
			</destination>
			<destination class="ChartDestination">
				<period type="time" value="5000"/>
				<property name="name" value="Response Time (GC)"/>
				<property name="group" value="${perfcake.scenario}_response_time"/>
				<property name="yAxis" value="Response Time [ms]"/>
				<property name="outputDir" value="${perfcake.reports.dir:./}${perfcake.scenario}-charts"/>
				<property name="attributes" value="Result,Average,Minimum,Maximum"/>
			</destination>
			<destination class="ConsoleDestination">
				<period type="time" value="5000"/>
			</destination>
		</reporter>
		<reporter class="ResponseTimeHistogramReporter">
			<property name="filter" value="true"/>
			<property name="maxExpectedValue" value="10000"/>
			<destination class="ChartDestination">
				<period type="time" value="${perfcake.performance.run.duration:300000}"/>
				<property name="yAxis" value="HDR Response time [ms]"/>
				<property name="group" value="hdr"/>
				<property name="name" value="HDR Response Time"/>
				<property name="attributes" value="perc*"/>
				<property name="type" value="bar"/>
				<property name="outputDir" value="${perfcake.reports.dir:./}${perfcake.scenario}-charts"/>
			</destination>
		</reporter>
		<reporter class="ClassifyingReporter">
			<property name="attribute" value="threadId"/>
			<property name="prefix" value="thread_"/>
			<destination class="ConsoleDestination">
				<period type="time" value="${perfcake.performance.run.duration:300000}"/>
			</destination>
			<destination class="ChartDestination">
				<period type="time" value="${perfcake.performance.run.duration:300000}"/>
				<property name="yAxis" value="Thread usage [messages]"/>
				<property name="group" value="threads"/>
				<property name="name" value="Thread usage"/>
				<property name="attributes" value="thread*"/>
				<property name="type" value="bar"/>
				<property name="outputDir" value="${perfcake.reports.dir:./}${perfcake.scenario}-charts"/>
			</destination>
		</reporter>
	</reporting>
	<messages>
		<message content="By this statement I lie!"/>
	</messages>
</scenario>
```

**Comment by pmacik** [comment]
The issue is still there:
```
[WARNING] 
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.apache.commons.collections4.list.CursorableLinkedList.broadcastNodeRemoved(CursorableLinkedList.java:334)
	at org.apache.commons.collections4.list.CursorableLinkedList.removeNode(CursorableLinkedList.java:247)
	at org.apache.commons.collections4.list.CursorableLinkedList$Cursor.remove(CursorableLinkedList.java:441)
	at org.perfcake.common.TimeSlidingWindow.gc(TimeSlidingWindow.java:175)
	at org.perfcake.common.TimeSlidingWindow.gc(TimeSlidingWindow.java:160)
	at org.perfcake.common.TimeSlidingWindow.forEach(TimeSlidingWindow.java:123)
	at org.perfcake.reporting.reporter.accumulator.AbstractTimeSlidingWindowAccumulator.getResult(AbstractTimeSlidingWindowAccumulator.java:69)
	at org.perfcake.reporting.reporter.AbstractReporter.lambda$publishAccumulatedResult$0(AbstractReporter.java:169)
	at org.perfcake.reporting.reporter.AbstractReporter$$Lambda$27/6952274.accept(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.perfcake.reporting.reporter.AbstractReporter.publishAccumulatedResult(AbstractReporter.java:169)
	at org.perfcake.reporting.reporter.StatsReporter.publishResult(StatsReporter.java:257)
	at org.perfcake.reporting.ReportManager.lambda$start$1(ReportManager.java:289)
	at org.perfcake.reporting.ReportManager$$Lambda$15/25263410.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pmacik** [comment]
Verified with 7.4, closling
