### ISSUE TITLE
IndexOutOfBoundsException when creating chart report

### ISSUE THREAD

**Issue by livthomas** [PerfCake/PerfCake#376]
I am getting the following exception when I run my performance tests based on PerfCake:

```
org.perfcake.PerfCakeException: Error generating messages: 

	at org.perfcake.scenario.Scenario.run(Scenario.java:143)
	at io.silverware.perftests.hystrix.HystrixRestPerformanceTest.testHystrixRest(HystrixRestPerformanceTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at org.perfcake.reporting.destination.c3chart.C3ChartData.combineWith(C3ChartData.java:204)
	at org.perfcake.reporting.destination.c3chart.C3ChartReport.combineCharts(C3ChartReport.java:236)
	at org.perfcake.reporting.destination.c3chart.C3ChartReport.analyzeMatchingCharts(C3ChartReport.java:192)
	at org.perfcake.reporting.destination.c3chart.C3ChartReport.createReport(C3ChartReport.java:90)
	at org.perfcake.reporting.destination.c3chart.C3ChartHelper.compileResults(C3ChartHelper.java:152)
	at org.perfcake.reporting.destination.ChartDestination.close(ChartDestination.java:168)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at org.perfcake.reporting.reporter.AbstractReporter.stop(AbstractReporter.java:351)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
	at org.perfcake.reporting.ReportManager.stop(ReportManager.java:360)
	at org.perfcake.message.generator.AbstractMessageGenerator.setStopTime(AbstractMessageGenerator.java:203)
	at org.perfcake.message.generator.DefaultMessageGenerator.shutdown(DefaultMessageGenerator.java:187)
	at org.perfcake.message.generator.DefaultMessageGenerator.generate(DefaultMessageGenerator.java:227)
	at org.perfcake.scenario.Scenario.run(Scenario.java:141)
	... 30 more
```

**Comment by marvec** [comment]
Could you please provide more details - which PerfCake version did you use? Please attach your scenario. Thanks.

**Comment by livthomas** [comment]
The scenario can be found in [SilverWare-PerfTests](https://github.com/livthomas/SilverWare-PerfTests/blob/devel/hystrix-perftests/src/test/resources/scenarios/hystrix-rest.xml) repository. The latest PerfCake 7.4 is used.

**Comment by marvec** [comment]
Is it possible that one of your previous runs reported no data? Basically you had a chart with no values displayed. Possible from a test that was stopped prematurely.

**Comment by livthomas** [comment]
I am not sure. It may be the case.
