### ISSUE TITLE
BindException during testing 

### ISSUE THREAD

**Issue by PatrikMajercik** [PerfCake/PerfCake#391]
I was trying to test something during PV260 seminar so I used the setup for this seminar (demos and scenarios). During testing sometimes starts occurring this exception (see below). But after a while testing continues normally.  

`java.net.BindException:` Address already in use: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_144]
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_144]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_144]
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_144]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_144]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_144]
        at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_144]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_144]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_144]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_144]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_144]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_144]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_144]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202) ~[?:1.8.0_144]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[?:1.8.0_144]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[?:1.8.0_144]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966) ~[?:1.8.0_144]
        at org.perfcake.message.sender.HttpSender.doSend(HttpSender.java:289) ~[perfcake-7.5.jar:?]
        at org.perfcake.message.sender.AbstractSender.send(AbstractSender.java:83) ~[perfcake-7.5.jar:?]
        at org.perfcake.message.generator.SenderTask.sendMessage(SenderTask.java:160) [perfcake-7.5.jar:?]
        at org.perfcake.message.generator.SenderTask.run(SenderTask.java:226) [perfcake-7.5.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
`

Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: C:\Program Files\Apache-maven-3.5.0\apache-maven-3.5.0
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_144\jre
Default locale: cs_CZ, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by pmacik** [comment]
@PatrikMajercik Thanks for reporting this.
Could you please provide the scenario and command, that you used?
Thanks

**Comment by marvec** [comment]
Hello, this is caused by too many open connections and is dependent on the operating system. You can try increasing sockets or files limits. Or you can limit the number of clients in the scenario. There is nothing we can do on our side. You simply asked PerfCake to do more than your OS is capable of. See https://stackoverflow.com/questions/4708649/java-net-bindexception-address-already-in-use-when-trying-to-do-rapid-socket
